//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PostirushkiNew
{
    using System;
    using System.Collections.Generic;
    
    public partial class Offer
    {
        public int IdOffer { get; set; }
        public System.DateTime Date { get; set; }
        public int IdShift { get; set; }
        public int IdWM { get; set; }
        public int IdPowder { get; set; }
        public int IdService { get; set; }
        public int IdCalculation { get; set; }
        public int IdStatus { get; set; }
    
        public virtual Calculation Calculation { get; set; }
        public virtual Powder Powder { get; set; }
        public virtual Service Service { get; set; }
        public virtual Shift Shift { get; set; }
        public virtual WashingMachine WashingMachine { get; set; }
        public virtual WashingStatus WashingStatus { get; set; }
    }
}
